# frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: clinc150
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: clinc150
      tier: frontend
  template:
    metadata:
      labels:
        app: clinc150
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: liablack/clinc150-frontend:latest
        resources: # <--- AGREGAR ESTO
          requests:
            cpu: "50m" # Solicitar 0.1 vCPU
            memory: "64Mi"
          limits:
            cpu: "100m" # Máximo 0.2 vCPU
            memory: "128Mi"
        ports:
        - containerPort: 80 # Puerto que Nginx usa internamente
        env: # <--- ¡AGREGA ESTAS LÍNEAS!
        - name: REACT_APP_API_URL
          value: "http://backend-clusterip:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: clinc150
spec:
  selector:
    app: clinc150      # Añadido para coincidir
    tier: frontend     # Debe coincidir con el Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer