# kubernetes/hpa-frontend.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  labels:
    app: clinc150
spec:
  scaleTargetRef:
    # Apunta al Deployment que definiste en frontend.yaml
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      # Escalar si la CPU excede el 50% de utilización (los frontends suelen ser más ligeros)
      target:
        type: Utilization
        averageUtilization: 50